server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # registerWithEureka=false + fetchRegistry=false 表明当前服务是 eureka server.
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/